function dJ_m_sym = dJm_n4(dLc1,dLc2,dLc3,dLc4,dq1,dq2,dq3,dq4)
%dJm_n4
%    dJ_m_sym = dJm_n4(dLc1,dLc2,dLc3,dLc4,DQ1,DQ2,DQ3,DQ4)

%    This function was generated by the Symbolic Math Toolbox version 9.1.
%    27-Nov-2022 19:36:24

t2 = dLc1.*dq1;
t3 = dLc2.*dq2;
t4 = dLc3.*dq3;
t5 = dLc4.*dq4;
dJ_m_sym = reshape([0.0,t2,t2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,t3,t3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,t4,t4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,t5,t5,0.0],[16,4]);
