function g_xi = g_xi_h4_n4(g,mu1,mu2,mu3,mu4,xi1,xi2,xi3,xi4,xi5,xi6,xi7,xi8,xi9,xi10,xi11,xi12,xi13,xi14)
%G_XI_H4_N4
%    G_XI = G_XI_H4_N4(G,MU1,MU2,MU3,MU4,XI1,XI2,XI3,XI4,XI5,XI6,XI7,XI8,XI9,XI10,XI11,XI12,XI13,XI14)

%    This function was generated by the Symbolic Math Toolbox version 9.1.
%    27-Nov-2022 19:36:24

t2 = cos(xi1);
t3 = sin(xi1);
t4 = mu3+mu4;
t6 = xi1+xi4+xi5;
t5 = mu2+t4;
t7 = cos(t6);
t8 = sin(t6);
t9 = t6+xi8+xi9;
t10 = t8.*xi6;
t11 = t8.*xi7;
t12 = cos(t9);
t13 = sin(t9);
t14 = t9+xi12+xi13;
t15 = t13.*xi10;
t16 = t13.*xi11;
t17 = sin(t14);
t18 = g.*mu2.*t10;
t19 = g.*mu3.*t15;
t20 = t17.*xi14;
t22 = t10+t11+t15;
t21 = g.*mu4.*t20;
t23 = g.*mu3.*t22;
t24 = t15+t16+t20;
t26 = t16+t20+t22;
t25 = g.*mu4.*t24;
t28 = g.*mu4.*t26;
t27 = t19+t25;
t29 = t18+t23+t28;
g_xi = [t18+t19+t21+g.*mu3.*t10+g.*mu3.*t11+g.*mu4.*t10+g.*mu4.*t11+g.*mu4.*t15+g.*mu4.*t16+g.*mu1.*t3.*xi2+g.*mu2.*t3.*xi2+g.*mu2.*t3.*xi3+g.*mu3.*t3.*xi2+g.*mu3.*t3.*xi3+g.*mu4.*t3.*xi2+g.*mu4.*t3.*xi3;-g.*t2.*(mu1+t5);-g.*t2.*t5;t29;t29;-g.*t5.*t7;-g.*t4.*t7;t27;t27;-g.*t4.*t12;-g.*mu4.*t12;t21;t21;-g.*mu4.*cos(t14);0.0;0.0];
