function m_map_sym = m_q2xi_n4(L1,L2,L3,L4,q1,q2,q3,q4,sq1,sq2,sq3,sq4)
%M_Q2XI_N4
%    M_MAP_SYM = M_Q2XI_N4(L1,L2,L3,L4,Q1,Q2,Q3,Q4,SQ1,SQ2,SQ3,SQ4)

%    This function was generated by the Symbolic Math Toolbox version 9.1.
%    27-Nov-2022 19:36:24

t2 = L1.*sq1;
t3 = L2.*sq2;
t4 = L3.*sq3;
t5 = L4.*sq4;
t6 = q1./2.0;
t7 = q2./2.0;
t8 = q3./2.0;
t9 = q4./2.0;
m_map_sym = [t6;t2;t2;t6;t7;t3;t3;t7;t8;t4;t4;t8;t9;t5;t5;t9];
