function xy_li_sym = pcc_xy_n4(L1,L2,L3,L4,cosc1,cosc2,cosc3,cosc4,q1,q2,q3,sinc1,sinc2,sinc3,sinc4)
%PCC_XY_N4
%    XY_LI_SYM = PCC_XY_N4(L1,L2,L3,L4,COSC1,COSC2,COSC3,COSC4,Q1,Q2,Q3,SINC1,SINC2,SINC3,SINC4)

%    This function was generated by the Symbolic Math Toolbox version 9.1.
%    27-Nov-2022 19:36:24

t2 = cos(q1);
t3 = sin(q1);
t4 = L1.*cosc1;
t5 = L1.*sinc1;
t6 = q1+q2;
t7 = cos(t6);
t8 = q3+t6;
t9 = sin(t6);
t10 = L2.*sinc2.*t3;
t13 = L2.*cosc2.*t2;
t14 = L2.*cosc2.*t3;
t15 = L2.*sinc2.*t2;
t11 = cos(t8);
t12 = sin(t8);
t16 = L3.*cosc3.*t7;
t17 = L3.*cosc3.*t9;
t18 = L3.*sinc3.*t7;
t19 = L3.*sinc3.*t9;
t20 = -t14;
t21 = -t17;
xy_li_sym = reshape([t5,t4,t5+t15+t20,t4+t10+t13,t5+t15+t18+t20+t21,t4+t10+t13+t16+t19,t5+t15+t18+t20+t21-L4.*cosc4.*t12+L4.*sinc4.*t11,t4+t10+t13+t16+t19+L4.*cosc4.*t11+L4.*sinc4.*t12],[2,4]);
